//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpacTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TpacTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: szszss.
        /// </summary>
        public static string About_Author {
            get {
                return ResourceManager.GetString("About_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string About_Close {
            get {
                return ResourceManager.GetString("About_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     TpacTool is a software for viewing and unpacking the tpac files of Mount&amp;Blade II: Bannerlord..
        /// </summary>
        public static string About_Intro {
            get {
                return ResourceManager.GetString("About_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website:.
        /// </summary>
        public static string About_Website {
            get {
                return ResourceManager.GetString("About_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry.
        /// </summary>
        public static string Asset_Type_Geometry {
            get {
                return ResourceManager.GetString("Asset_Type_Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Asset_Type_Material {
            get {
                return ResourceManager.GetString("Asset_Type_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Asset_Type_Model {
            get {
                return ResourceManager.GetString("Asset_Type_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morph.
        /// </summary>
        public static string Asset_Type_MorphAnimation {
            get {
                return ResourceManager.GetString("Asset_Type_MorphAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle.
        /// </summary>
        public static string Asset_Type_Particle {
            get {
                return ResourceManager.GetString("Asset_Type_Particle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physics Shape.
        /// </summary>
        public static string Asset_Type_PhysicsShape {
            get {
                return ResourceManager.GetString("Asset_Type_PhysicsShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVF.
        /// </summary>
        public static string Asset_Type_ProceduralVectorField {
            get {
                return ResourceManager.GetString("Asset_Type_ProceduralVectorField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shader.
        /// </summary>
        public static string Asset_Type_Shader {
            get {
                return ResourceManager.GetString("Asset_Type_Shader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation.
        /// </summary>
        public static string Asset_Type_SkeletalAnimation {
            get {
                return ResourceManager.GetString("Asset_Type_SkeletalAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skeleton.
        /// </summary>
        public static string Asset_Type_Skeleton {
            get {
                return ResourceManager.GetString("Asset_Type_Skeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture.
        /// </summary>
        public static string Asset_Type_Texture {
            get {
                return ResourceManager.GetString("Asset_Type_Texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string AssetTree_Filter_Tooltip {
            get {
                return ResourceManager.GetString("AssetTree_Filter_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filter pattern.
        /// </summary>
        public static string AssetTree_FilterRemove_Tooltip {
            get {
                return ResourceManager.GetString("AssetTree_FilterRemove_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouped by package.
        /// </summary>
        public static string AssetTree_Grouped_Tooltip {
            get {
                return ResourceManager.GetString("AssetTree_Grouped_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Loading_Cancel {
            get {
                return ResourceManager.GetString("Loading_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching tpac ....
        /// </summary>
        public static string Loading_Searching {
            get {
                return ResourceManager.GetString("Loading_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading_Title {
            get {
                return ResourceManager.GetString("Loading_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the AssetPackages folder.
        /// </summary>
        public static string Main_Dialog_SelectAssetPackages {
            get {
                return ResourceManager.GetString("Main_Dialog_SelectAssetPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Main_Menu_File {
            get {
                return ResourceManager.GetString("Main_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Main_Menu_File_Exit {
            get {
                return ResourceManager.GetString("Main_Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open AssetPackages Folder ....
        /// </summary>
        public static string Main_Menu_File_OpenAssetFolder {
            get {
                return ResourceManager.GetString("Main_Menu_File_OpenAssetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setti_ngs.
        /// </summary>
        public static string Main_Menu_Settings {
            get {
                return ResourceManager.GetString("Main_Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Main_Menu_Settings_About {
            get {
                return ResourceManager.GetString("Main_Menu_Settings_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Main_Menu_Settings_Languages {
            get {
                return ResourceManager.GetString("Main_Menu_Settings_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Main_Menu_Settings_Languages_Default {
            get {
                return ResourceManager.GetString("Main_Menu_Settings_Languages_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all non-tileset textures to ....
        /// </summary>
        public static string Material_Dialog_SelectExportDir {
            get {
                return ResourceManager.GetString("Material_Dialog_SelectExportDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Material_Export {
            get {
                return ResourceManager.GetString("Material_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred format.
        /// </summary>
        public static string Material_Export_PreferredFormat {
            get {
                return ResourceManager.GetString("Material_Export_PreferredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string Material_Export_PreferredFormat_Any {
            get {
                return ResourceManager.GetString("Material_Export_PreferredFormat_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDS first.
        /// </summary>
        public static string Material_Export_PreferredFormat_Dds {
            get {
                return ResourceManager.GetString("Material_Export_PreferredFormat_Dds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG first.
        /// </summary>
        public static string Material_Export_PreferredFormat_Png {
            get {
                return ResourceManager.GetString("Material_Export_PreferredFormat_Png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which format is preferred for export..
        /// </summary>
        public static string Material_Export_PreferredFormat_Tooltip {
            get {
                return ResourceManager.GetString("Material_Export_PreferredFormat_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Material_Preview {
            get {
                return ResourceManager.GetString("Material_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Material_Properties {
            get {
                return ResourceManager.GetString("Material_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha Test:.
        /// </summary>
        public static string Material_Properties_AlphaTest {
            get {
                return ResourceManager.GetString("Material_Properties_AlphaTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blend Mode:.
        /// </summary>
        public static string Material_Properties_BlendMode {
            get {
                return ResourceManager.GetString("Material_Properties_BlendMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        public static string Material_Properties_Flags {
            get {
                return ResourceManager.GetString("Material_Properties_Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Material_Properties_Info {
            get {
                return ResourceManager.GetString("Material_Properties_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shader:.
        /// </summary>
        public static string Material_Properties_Shader {
            get {
                return ResourceManager.GetString("Material_Properties_Shader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shader Hints.
        /// </summary>
        public static string Material_Properties_ShaderHints {
            get {
                return ResourceManager.GetString("Material_Properties_ShaderHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show empty slots.
        /// </summary>
        public static string Material_Properties_ShowEmptySlots {
            get {
                return ResourceManager.GetString("Material_Properties_ShowEmptySlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the texture slots which aren&apos;t assigned texture.
        /// </summary>
        public static string Material_Properties_ShowEmptySlots_Tooltip {
            get {
                return ResourceManager.GetString("Material_Properties_ShowEmptySlots_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textures:.
        /// </summary>
        public static string Material_Properties_Textures {
            get {
                return ResourceManager.GetString("Material_Properties_Textures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex Layout Hints.
        /// </summary>
        public static string Material_Properties_VertexLayoutHints {
            get {
                return ResourceManager.GetString("Material_Properties_VertexLayoutHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export model to ....
        /// </summary>
        public static string Model_Dialog_SelectExportFile {
            get {
                return ResourceManager.GetString("Model_Dialog_SelectExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Model_Export {
            get {
                return ResourceManager.GetString("Model_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material &amp; Texture.
        /// </summary>
        public static string Model_Export_Material {
            get {
                return ResourceManager.GetString("Model_Export_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only export diffuse (color) texture.
        /// </summary>
        public static string Model_Export_Material_DiffuseOnly {
            get {
                return ResourceManager.GetString("Model_Export_Material_DiffuseOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the diffuse (ie color) texture will be exported. Note that this option will also affect the model file itself. The materials in the model file will no longer include textures other than diffuse..
        /// </summary>
        public static string Model_Export_Material_DiffuseOnly_Tooltip {
            get {
                return ResourceManager.GetString("Model_Export_Material_DiffuseOnly_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to same folder.
        /// </summary>
        public static string Model_Export_Material_ExportSame {
            get {
                return ResourceManager.GetString("Model_Export_Material_ExportSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export the texture files to the same folder with the exported model..
        /// </summary>
        public static string Model_Export_Material_ExportSame_Tooltip {
            get {
                return ResourceManager.GetString("Model_Export_Material_ExportSame_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to sub folder.
        /// </summary>
        public static string Model_Export_Material_ExportSub {
            get {
                return ResourceManager.GetString("Model_Export_Material_ExportSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export the texture files to a folder named after the exported model..
        /// </summary>
        public static string Model_Export_Material_ExportSub_Tooltip {
            get {
                return ResourceManager.GetString("Model_Export_Material_ExportSub_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t export.
        /// </summary>
        public static string Model_Export_Material_NoExport {
            get {
                return ResourceManager.GetString("Model_Export_Material_NoExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not export the texture files which the model uses..
        /// </summary>
        public static string Model_Export_Material_NoExport_Tooltip {
            get {
                return ResourceManager.GetString("Model_Export_Material_NoExport_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string Model_Export_Misc {
            get {
                return ResourceManager.GetString("Model_Export_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAE: Fix the bone connections for Blender.
        /// </summary>
        public static string Model_Export_Misc_FixBoneConnect {
            get {
                return ResourceManager.GetString("Model_Export_Misc_FixBoneConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add metadata for Blender to identify bone connections. Even if you do not check this option, the connection can be repaired by adjusting the configuration of the DAE importer of Blender..
        /// </summary>
        public static string Model_Export_Misc_FixBoneConnect_Tooltip {
            get {
                return ResourceManager.GetString("Model_Export_Misc_FixBoneConnect_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larger scale.
        /// </summary>
        public static string Model_Export_Misc_LargerScale {
            get {
                return ResourceManager.GetString("Model_Export_Misc_LargerScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlarging the size of the exported model. For the formats which support node (eg DAE) it will enlarge the scale of root node.  For others (eg OBJ) it will directly enlarge the mesh..
        /// </summary>
        public static string Model_Export_Misc_LargerScale_Tooltip {
            get {
                return ResourceManager.GetString("Model_Export_Misc_LargerScale_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative-Y-forward axis.
        /// </summary>
        public static string Model_Export_Misc_NYForward {
            get {
                return ResourceManager.GetString("Model_Export_Misc_NYForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default, the exported model faces to +Y. Check this option to make it facing to -Y..
        /// </summary>
        public static string Model_Export_Misc_NYForward_Tooltip {
            get {
                return ResourceManager.GetString("Model_Export_Misc_NYForward_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBJ: Y-upward axis.
        /// </summary>
        public static string Model_Export_Misc_YUpAxis {
            get {
                return ResourceManager.GetString("Model_Export_Misc_YUpAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default, the exported model uses the Z axis as the upward axis. However, some OBJ importers use the Y axis as the upward axis. Check this option to export the OBJ model with Y-upward axis style..
        /// </summary>
        public static string Model_Export_Misc_YUpAxis_Tooltip {
            get {
                return ResourceManager.GetString("Model_Export_Misc_YUpAxis_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skeleton.
        /// </summary>
        public static string Model_Export_Skeleton {
            get {
                return ResourceManager.GetString("Model_Export_Skeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horse.
        /// </summary>
        public static string Model_Export_Skeleton_Horse {
            get {
                return ResourceManager.GetString("Model_Export_Skeleton_Horse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        public static string Model_Export_Skeleton_Human {
            get {
                return ResourceManager.GetString("Model_Export_Skeleton_Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Model_Export_Skeleton_Other {
            get {
                return ResourceManager.GetString("Model_Export_Skeleton_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Model_Export_Type {
            get {
                return ResourceManager.GetString("Model_Export_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rigged.
        /// </summary>
        public static string Model_Export_Type_Rigged {
            get {
                return ResourceManager.GetString("Model_Export_Type_Rigged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static.
        /// </summary>
        public static string Model_Export_Type_Static {
            get {
                return ResourceManager.GetString("Model_Export_Type_Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per-mesh Properties.
        /// </summary>
        public static string Model_PerMeshProperties {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing Material.
        /// </summary>
        public static string Model_PerMeshProperties_CM {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Drag Multiplier:.
        /// </summary>
        public static string Model_PerMeshProperties_CM_ADM {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM_ADM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor Stiffness:.
        /// </summary>
        public static string Model_PerMeshProperties_CM_AS {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bending Stiffness:.
        /// </summary>
        public static string Model_PerMeshProperties_CM_BS {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM_BS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damping:.
        /// </summary>
        public static string Model_PerMeshProperties_CM_Damping {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM_Damping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravity:.
        /// </summary>
        public static string Model_PerMeshProperties_CM_Gravity {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM_Gravity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear Inertia:.
        /// </summary>
        public static string Model_PerMeshProperties_CM_LI {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM_LI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear Velocity Multiplier:.
        /// </summary>
        public static string Model_PerMeshProperties_CM_LVM {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM_LVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Linear Velocity:.
        /// </summary>
        public static string Model_PerMeshProperties_CM_MLV {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM_MLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Model_PerMeshProperties_CM_Name {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shearing Stiffness:.
        /// </summary>
        public static string Model_PerMeshProperties_CM_ShS {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM_ShS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretching Stiffness:.
        /// </summary>
        public static string Model_PerMeshProperties_CM_StS {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM_StS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind:.
        /// </summary>
        public static string Model_PerMeshProperties_CM_Wind {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_CM_Wind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face:.
        /// </summary>
        public static string Model_PerMeshProperties_Face {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_Face", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        public static string Model_PerMeshProperties_Flags {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Morph.
        /// </summary>
        public static string Model_PerMeshProperties_HasMorph {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_HasMorph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Model_PerMeshProperties_Info {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Rigged.
        /// </summary>
        public static string Model_PerMeshProperties_IsRigged {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_IsRigged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lod:.
        /// </summary>
        public static string Model_PerMeshProperties_Lod {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_Lod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material:.
        /// </summary>
        public static string Model_PerMeshProperties_Material {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Hints.
        /// </summary>
        public static string Model_PerMeshProperties_MaterialHints {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_MaterialHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Model_PerMeshProperties_Name {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecMat:.
        /// </summary>
        public static string Model_PerMeshProperties_SecMat {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_SecMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex:.
        /// </summary>
        public static string Model_PerMeshProperties_Vertex {
            get {
                return ResourceManager.GetString("Model_PerMeshProperties_Vertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Model_Preview {
            get {
                return ResourceManager.GetString("Model_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOD:.
        /// </summary>
        public static string Model_Preview_Lod {
            get {
                return ResourceManager.GetString("Model_Preview_Lod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Model_Preview_Show {
            get {
                return ResourceManager.GetString("Model_Preview_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory doesn&apos;t exist.
        /// </summary>
        public static string Msgbox_DirNotExisting {
            get {
                return ResourceManager.GetString("Msgbox_DirNotExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Msgbox_Error {
            get {
                return ResourceManager.GetString("Msgbox_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Msgbox_Info {
            get {
                return ResourceManager.GetString("Msgbox_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file loaded. (No tpac file in any sub directory).
        /// </summary>
        public static string Msgbox_NoFileLoaded {
            get {
                return ResourceManager.GetString("Msgbox_NoFileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tpac file found in the top directory. Go on? (Will search sub directories).
        /// </summary>
        public static string Msgbox_TpacNotFound {
            get {
                return ResourceManager.GetString("Msgbox_TpacNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus:.
        /// </summary>
        public static string Preview_Center {
            get {
                return ResourceManager.GetString("Preview_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center of Geometry.
        /// </summary>
        public static string Preview_Center_Geometry {
            get {
                return ResourceManager.GetString("Preview_Center_Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center of Mass.
        /// </summary>
        public static string Preview_Center_Mass {
            get {
                return ResourceManager.GetString("Preview_Center_Mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        public static string Preview_Center_Origin {
            get {
                return ResourceManager.GetString("Preview_Center_Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the focal point of rotation and scaling..
        /// </summary>
        public static string Preview_Center_Tooltip {
            get {
                return ResourceManager.GetString("Preview_Center_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inertia.
        /// </summary>
        public static string Preview_Inertia {
            get {
                return ResourceManager.GetString("Preview_Inertia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable inertia for rotation and scaling..
        /// </summary>
        public static string Preview_Inertia_Tooltip {
            get {
                return ResourceManager.GetString("Preview_Inertia_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Scale.
        /// </summary>
        public static string Preview_Keepscale {
            get {
                return ResourceManager.GetString("Preview_Keepscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep the scale of the preview model in the screen when selecting other asset..
        /// </summary>
        public static string Preview_Keepscale_Tooltip {
            get {
                return ResourceManager.GetString("Preview_Keepscale_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lights:.
        /// </summary>
        public static string Preview_Lights {
            get {
                return ResourceManager.GetString("Preview_Lights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quad Lights.
        /// </summary>
        public static string Preview_Lights_Quad {
            get {
                return ResourceManager.GetString("Preview_Lights_Quad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Light.
        /// </summary>
        public static string Preview_Lights_Single {
            get {
                return ResourceManager.GetString("Preview_Lights_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the light sources in the scene..
        /// </summary>
        public static string Preview_Lights_Tooltip {
            get {
                return ResourceManager.GetString("Preview_Lights_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tri Lights.
        /// </summary>
        public static string Preview_Lights_Tri {
            get {
                return ResourceManager.GetString("Preview_Lights_Tri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot preview this texture because its format is unsupported: {0}.
        /// </summary>
        public static string Preview_Msg_TextureFormatUnsupported {
            get {
                return ResourceManager.GetString("Preview_Msg_TextureFormatUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot preview nor export this texture because its data are stored in the external TileSets file..
        /// </summary>
        public static string Preview_Msg_TextureHasNoData {
            get {
                return ResourceManager.GetString("Preview_Msg_TextureHasNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot preview this texture because of its size (&gt;100MB).
        /// </summary>
        public static string Preview_Msg_TextureSizeTooLarge {
            get {
                return ResourceManager.GetString("Preview_Msg_TextureSizeTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Grid.
        /// </summary>
        public static string Preview_Showgrid {
            get {
                return ResourceManager.GetString("Preview_Showgrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the grid of ground..
        /// </summary>
        public static string Preview_Showgrid_Tooltip {
            get {
                return ResourceManager.GetString("Preview_Showgrid_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export texture to ....
        /// </summary>
        public static string Texture_Dialog_SelectExportFile {
            get {
                return ResourceManager.GetString("Texture_Dialog_SelectExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Texture_Export {
            get {
                return ResourceManager.GetString("Texture_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested format: {0}.
        /// </summary>
        public static string Texture_Export_SuggestedFormat {
            get {
                return ResourceManager.GetString("Texture_Export_SuggestedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        public static string Texture_Flags {
            get {
                return ResourceManager.GetString("Texture_Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Texture_Preview {
            get {
                return ResourceManager.GetString("Texture_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channal.
        /// </summary>
        public static string Texture_Preview_Channel {
            get {
                return ResourceManager.GetString("Texture_Preview_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha.
        /// </summary>
        public static string Texture_Preview_Channel_Alpha {
            get {
                return ResourceManager.GetString("Texture_Preview_Channel_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Texture_Preview_Channel_Auto {
            get {
                return ResourceManager.GetString("Texture_Preview_Channel_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R as Gray.
        /// </summary>
        public static string Texture_Preview_Channel_RGray {
            get {
                return ResourceManager.GetString("Texture_Preview_Channel_RGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which color channels are displayed during preview..
        /// </summary>
        public static string Texture_Preview_Channel_Tooltip {
            get {
                return ResourceManager.GetString("Texture_Preview_Channel_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clamp.
        /// </summary>
        public static string Texture_Preview_Clamp {
            get {
                return ResourceManager.GetString("Texture_Preview_Clamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Size.
        /// </summary>
        public static string Texture_Preview_Clamp_Full {
            get {
                return ResourceManager.GetString("Texture_Preview_Clamp_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrict the size of the preview texture. Smaller clamp size can make the texture load faster..
        /// </summary>
        public static string Texture_Preview_Clamp_Tooltip {
            get {
                return ResourceManager.GetString("Texture_Preview_Clamp_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Texture_Properties {
            get {
                return ResourceManager.GetString("Texture_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array:.
        /// </summary>
        public static string Texture_Properties_Array {
            get {
                return ResourceManager.GetString("Texture_Properties_Array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:.
        /// </summary>
        public static string Texture_Properties_Format {
            get {
                return ResourceManager.GetString("Texture_Properties_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Texture_Properties_Info {
            get {
                return ResourceManager.GetString("Texture_Properties_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mipmap:.
        /// </summary>
        public static string Texture_Properties_Mipmap {
            get {
                return ResourceManager.GetString("Texture_Properties_Mipmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string Texture_Properties_Size {
            get {
                return ResourceManager.GetString("Texture_Properties_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Flags.
        /// </summary>
        public static string Texture_System_Flags {
            get {
                return ResourceManager.GetString("Texture_System_Flags", resourceCulture);
            }
        }
    }
}
